export * from './Home'
export * from './TvShows'
export * from './Movies'
export * from './TvShowDetails'
export * from './MovieDetails'
export * from './Profile'
export * from './SIgnup'
export * from './Login'
