export * from './Home'
export * from './Series'
export * from './Singles'
export * from './SeriesDetails'
export * from './SingleItemDetails'
export * from './Profile'
export * from './Signup'
export * from './Login'
